# -*- coding: utf-8 -*-
"""Tkinter_Tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C9XUu--sr8HgV5qE14UF6o-G7LRu1_nW
"""

#!/usr/bin/python

# Create a GUI Page

# import everything from tkinter module
from tkinter import *   
 
# create a tkinter window
root = Tk()             
 
# Open window having dimension width x height
root.geometry('300x400')
 
root.mainloop()

"""# Button Simulation

***********Create Simple Button
"""

# import everything from tkinter module
from tkinter import *   
 
# create a tkinter window
root = Tk()             
 
# Open window having dimension width x height
root.geometry('300x400')
 
btn = Button(root,text = "Submit")  
  
btn.pack()  
  
root.mainloop()

"""******Multiple Buttons with customization using pack to place at different position"""

# import everything from tkinter module
from tkinter import *   
 
# create a tkinter window
root = Tk()             
 
# Open window having dimension width x height
root.geometry('300x400')
 
btn1 = Button(root,text = "Button 1", activeforeground = "blue", activebackground = "pink",height = 5, width = 10)  
btn2 = Button(root,text = "Button 2", activeforeground = "blue", activebackground = "pink",height = 5, width = 10)
btn3 = Button(root,text = "Button 3", activeforeground = "blue", activebackground = "pink",pady=10)

btn1.pack(side = LEFT)  
  
btn2.pack(side = RIGHT)  
  
btn3.pack(side = TOP)  
  
root.mainloop()

"""*****Place the buttons at specific location"""

# import everything from tkinter module
from tkinter import *   
 
# create a tkinter window
root = Tk()             
 
# Open window having dimension width x height
root.geometry('300x400')
 
btn1 = Button(root,text = "Button 1", activeforeground = "blue", activebackground = "pink",height = 3, width = 7)  
btn2 = Button(root,text = "Button 2", activeforeground = "blue", activebackground = "pink",height = 3, width = 7)
btn3 = Button(root,text = "Button 3", activeforeground = "blue", activebackground = "pink",height = 3, width = 7)

btn1.place(x=25, y=220)  
btn2.place(x=125, y=220)  
btn3.place(x=220, y=220)

root.mainloop()

"""***** **Button with Comands"""

# import everything from tkinter module
from tkinter import * 
import tkinter.messagebox
 
# create a tkinter window
root = Tk()             
 
# Open window having dimension width x height
root.geometry('300x400')

def submitfn():  
    messagebox.showinfo("Response", "Successfully Submitted")  
    
def closefn():
     root.destroy()
btn1 = Button(root,text = "Submit", command = submitfn, activeforeground = "blue", activebackground = "pink",height = 3, width = 7)  
btn2 = Button(root,text = "Close", command = closefn, activeforeground = "blue", activebackground = "pink",height = 3, width = 7)


btn1.place(x=75, y=220)  
btn2.place(x=180, y=220)  


root.mainloop()

"""# Textbox (Entry) Simulation

*****Text Box using Entry
"""

from tkinter import * 

root = Tk()
root.geometry('300x400')
L1 = Label(root, text="User Name :")
L1.pack( side = LEFT)
E1 = Entry(root, bd =5)
E1.pack(side = LEFT)

root.mainloop()

"""********Placing text box at specific location """

from tkinter import * 

root = Tk()
name = tkinter.StringVar()  
password = tkinter.StringVar()

root.geometry('300x400')
Label1 = Label(root, text="User Name :")
Label1.pack( side = LEFT)
Entry1 = Entry(root,textvariable=name)
Entry1.pack(side = LEFT)

Label2 = Label(root, text="Password :")
Label2.pack( side = LEFT)
Entry2 = Entry(root, show="*",textvariable=password)
Entry2.pack(side = LEFT)

Label1.place(x=20, y=220)  
Entry1.place(x=100, y=220)  

Label2.place(x=20, y=250)  
Entry2.place(x=100, y=250)

print(name)
print(password)
root.mainloop()

"""********Get the entered text box data and display it"""

# Login info
from tkinter import * 
import tkinter.messagebox
root = Tk()
root.title('Login') 
name = tkinter.StringVar()  
password = tkinter.StringVar()

def submitfn():  
    messagebox.showinfo("Response", "Successfully Submitted")  
    namevar=name.get()
    passvar=password.get()
     
    print("The name is : " + namevar)
    print("The password is : " + passvar)
     
    name.set("")
    password.set("")
def closefn():
     root.destroy()

root.geometry('300x400')
Label1 = Label(root, text="User Name :")
#Label1.pack( side = LEFT)
Entry1 = Entry(root,textvariable=name)
#Entry1.pack(side = LEFT)

Label2 = Label(root, text="Password :")
#Label2.pack( side = LEFT)
Entry2 = Entry(root, show="*",textvariable=password)
#Entry2.pack(side = LEFT)


     
btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

Label1.place(x=20, y=220)  
Entry1.place(x=100, y=220)  

Label2.place(x=20, y=250)  
Entry2.place(x=100, y=250)

btn1.place(x=90, y=280)  
btn2.place(x=170, y=280) 

root.mainloop()

"""******Place the textboxes and label using grid and also gete the entered text string"""

# Login Info using grid
from tkinter import * 
import tkinter.messagebox
root = Tk()
root.title('Login') 
name = tkinter.StringVar()  
password = tkinter.StringVar()

def submitfn():  
    messagebox.showinfo("Response", "Successfully Submitted")  
    namevar=name.get()
    passvar=password.get()
     
    print("The name is : " + namevar)
    print("The password is : " + passvar)
     
    name.set("")
    password.set("")
def closefn():
     root.destroy()

root.geometry('300x400')
Label1 = Label(root, text="User Name :")
#Label1.pack( side = LEFT)
Entry1 = Entry(root,textvariable=name)
#Entry1.pack(side = LEFT)

Label2 = Label(root, text="Password :")
#Label2.pack( side = LEFT)
Entry2 = Entry(root, show="*",textvariable=password)

     
btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

 


Label1.grid(row=0,column=0)
Entry1.grid(row=0,column=1)
Label2.grid(row=1,column=0)
Entry2.grid(row=1,column=1)
btn1.grid(row=2,column=0)
btn2.grid(row=2,column=1)

root.mainloop()

"""# Simulation of Checkbox, Radion Button and List Box

******Checkbox simulation and get the selected checkbox data
"""

# Checkbox, Radio Button, Listbox

# Login Info using grid
from tkinter import * 
from itertools import compress   # select the options using boolen index
import tkinter.messagebox
root = Tk()
root.title('Login')
root.geometry('300x400')

CheckVar1 = IntVar()
CheckVar2 = IntVar()
CheckVar3 = IntVar()

def submitfn():  
    messagebox.showinfo("Response", "Successfully Submitted")  
    check1=CheckVar1.get()
    check2=CheckVar2.get()
    check3=CheckVar3.get()
    intr=['Music','Video','Dance']
    var=[check1,check2,check3]
    intrst = list(compress(intr, var))
    print("The interests is/are : ", intrst)
    
     
    #name.set("")
    #password.set("")
def closefn():
     root.destroy()

Label = Label(root, text="Interest :")
Check1 = Checkbutton(root, text = "Music", variable = CheckVar1,onvalue = 1, offvalue = 0, height=2,width = 10)
Check2 = Checkbutton(root, text = "Video", variable = CheckVar2,onvalue = 1, offvalue = 0, height=2, width = 10)
Check3 = Checkbutton(root, text = "Dance", variable = CheckVar3,onvalue = 1, offvalue = 0, height=2, width = 10)

btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

Label.place(x=20, y=100) 
Check1.place(x=70, y=100)  
Check2.place(x=70, y=125)
Check3.place(x=70, y=150)

btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)

#Check1.grid(row=0,column=0)
#Check2.grid(row=1,column=0)
#Check3.grid(row=2,column=0)

root.mainloop()

"""******Radio button and get the selected radio button data"""

# Checkbox, Radio Button, Listbox

# Login Info using grid
from tkinter import * 
from itertools import compress   # select the options using boolen index
import tkinter.messagebox
root = Tk()
root.title('Login')
root.geometry('300x400')

RadioVar1 = IntVar()
RadioVar2 = IntVar()


def submitfn():  
    messagebox.showinfo("Response", "Successfully Submitted")  
    radio1=RadioVar1.get()
    radio2=RadioVar2.get()
    gen=['Male','Female']
    var=[radio1,radio2]
    gender = list(compress(gen, var))
    print("The gender is : ", gender)
    
     
    #name.set("")
    #password.set("")
def closefn():
     root.destroy()

Label = Label(root, text="Gender :")
Radio1 = Radiobutton(root, text = "Male", variable = RadioVar1,value = 1, height=2,width = 10)
Radio2 = Radiobutton(root, text = "Female", variable = RadioVar2,value = 2, height=2, width = 10)


btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

Label.place(x=20, y=107) 
Radio1.place(x=70, y=100)  
Radio2.place(x=150, y=100)


btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)

#Radio1.grid(row=0,column=0)
#Radio2.grid(row=1,column=0)
#Check3.grid(row=2,column=0)

root.mainloop()

"""******List box and get the selected option from the list box (Both single select and multiple select) """

# List box simulation both for single select and multiple select

from tkinter import * 
from itertools import compress   # select the options using boolen index
import tkinter.messagebox
root = Tk()
root.title('Login')
root.geometry('300x400')

def submitfn():
    prog=[]              # initilize to keep the multiple option
    messagebox.showinfo("Response", "Successfully Submitted") 
    valop=listb.curselection()  # it extract the list option index as an tuple
    valop=list(valop)           # convert the index tuple to list
    for i in valop:
        prog.append(listb.get(i))  # accessing the options through their index and appended on the prog
    print("The Programming is : ", prog)
    

def closefn():
     root.destroy()


Label = Label(root, text="Programming Language Known:")
#listb = Listbox(root, height = 10,width = 15,bg = "grey",activestyle = 'dotbox',fg = "yellow")
#listb = Listbox(root,selectmode='single')   # for selecting single value only
listb = Listbox(root,selectmode="multiple")  # for selecting multiple values

listb.insert(1, "Python")
listb.insert(2, "Java")
listb.insert(3, "C/C++")
listb.insert(4, "HTML")
listb.insert(5, "MATLAB")

btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 


Label.place(x=20, y=70) 
listb.place(x=100, y=100)
btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)


root.mainloop()

# List box simulation both for single select and multiple select

from tkinter import * 
from itertools import compress   # select the options using boolen index
import tkinter.messagebox
root = Tk()
root.title('Login')
root.geometry('300x400')

def submitfn():
    prog=[]              # initilize to keep the multiple option
    messagebox.showinfo("Response", "Successfully Submitted") 
    valop=listb.curselection()  # it extract the list option index as an tuple
    valop=list(valop)           # convert the index tuple to list
    for i in valop:
        prog.append(listb.get(i))  # accessing the options through their index and appended on the prog
    print("The Programming is : ", prog)
    

def closefn():
     root.destroy()


Label = Label(root, text="Programming Language Known:")
#listb = Listbox(root, height = 10,width = 15,bg = "grey",activestyle = 'dotbox',fg = "yellow")
#listb = Listbox(root,selectmode='single')   # for selecting single value only
listb = Listbox(root,selectmode="multiple")  # for selecting multiple values

listb.insert(1, "Python")
listb.insert(2, "Java")
listb.insert(3, "C/C++")
listb.insert(4, "HTML")
listb.insert(5, "MATLAB")

btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 


Label.place(x=20, y=70) 
listb.place(x=100, y=100)
btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)


root.mainloop()

"""# Dropdown menu and menubar

*****Drop down menu and get the selected option from the menu
"""

# Import module

from tkinter import * 
from itertools import compress   # select the options using boolen index
import tkinter.messagebox

root = Tk()
root.title('Login')
root.geometry('300x400')

# Change the label text
def submitfn():
	#label.config( text = clicked.get() )
    messagebox.showinfo("Response", "Successfully Submitted")  
    selval=var.get()
    print("Highest Qualification is : ", selval)

def closefn():
    root.destroy()
# Dropdown menu options
options = ["HighSchool","Intermediate","B.Tech","M.Tech","Ph.D"]
var = StringVar()
var.set( "Select" )

Label = Label(root, text="Highest Qualification:")

drop = OptionMenu( root , var , *options )


btn1 = Button(root,text = "Submit", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 


Label.place(x=20, y=70) 
drop.place(x=150, y=70)
btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)

root.mainloop()

"""******File Menubar with different options"""

# importing only those functions
# which are needed
from tkinter import *
#from tkinter.ttk import *
#from time import strftime

# creating tkinter window
root = Tk()
root.title('File Manager')
root.geometry('300x400')
# Creating Menubar
menubar = Menu(root)

# Adding File Menu and commands
file = Menu(menubar, tearoff = 0)
menubar.add_cascade(label ='File', menu = file)
file.add_command(label ='New', command = None)
file.add_command(label ='Open', command = None)
file.add_command(label ='Save', command = None)
file.add_separator()
file.add_command(label ='Exit', command = root.destroy)

# Adding Edit Menu and commands
edit = Menu(menubar, tearoff = 0)
menubar.add_cascade(label ='Edit', menu = edit)
edit.add_command(label ='Cut', command = None)
edit.add_command(label ='Copy', command = None)
edit.add_command(label ='Paste', command = None)
edit.add_command(label ='Select All', command = None)
edit.add_separator()
edit.add_command(label ='Find...', command = None)
edit.add_command(label ='Replace', command = None)

# Adding Help Menu
help_ = Menu(menubar, tearoff = 0)
menubar.add_cascade(label ='Help', menu = help_)
help_.add_command(label ='Demo', command = None)
help_.add_separator()
help_.add_command(label ='About', command = None)

# display Menu
root.config(menu = menubar)
root.mainloop()

"""# Image inside GUI Simulation using Canvas

******Display an image using PIL using Canvas
"""

# Display an image on GUI using PIL
from tkinter import *  
from PIL import ImageTk,Image  
root = Tk()  
canvas = Canvas(root, width = 300, height = 300)  
canvas.pack()  
img = ImageTk.PhotoImage(Image.open("photo.JPG"))  
canvas.create_image(20, 20, anchor=NW, image=img) 
root.mainloop()

"""******Create a rectangle using canvas"""

# Create a rectangle of specified size on Canvas Tkinter
from tkinter import *  
root = Tk()  
root.geometry('300x400')
canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")
root.mainloop()

"""******Create a rectangle and put text inside it"""

# Create a rectangle of specified size on Canvas Tkinter and label insid the rectangle
from tkinter import *  
root = Tk()  
root.geometry('300x400')
canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")
Label = Label(root, text="Paste Passport Photo")
Label.place(x=90,y=120)
root.mainloop()

"""******Create a rectangle and place an image inside it using PIL"""

# Create a rectangle of specified size on Canvas Tkinter 
# Insert a PIL Image
from tkinter import * 
from PIL import ImageTk,Image

root = Tk()  
root.geometry('300x400')

canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")

#Label = Label(root, text="Paste Passport Photo")
#Label.place(x=90,y=120)

img = ImageTk.PhotoImage(Image.open("photo.JPG"))
canvas.create_image(30, 30, anchor=NW, image=img)

root.mainloop()

"""******Create a rectangle and place an image inside it using PIL (Another approach)"""

# Create a rectangle of specified size on Canvas Tkinter 
# Insert a PIL Image (Anothe Syntax)
from tkinter import * 
from PIL import ImageTk,Image

root = Tk()  
root.geometry('300x400')

canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")

#Label = Label(root, text="Paste Passport Photo")
#Label.place(x=90,y=120)

im=Image.open("photo.JPG")
img = ImageTk.PhotoImage(im)
canvas.create_image(30, 30, anchor=NW, image=img)

root.mainloop()

"""******Create a rectangle and place an image inside it using opencv through PIL"""

# Create a rectangle of specified size on Canvas Tkinter 
# Insert a Computer Vision image through PIL object (Anothe Approach)
from tkinter import * 
from PIL import ImageTk,Image
import cv2

root = Tk()  
root.geometry('300x400')

canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")

#Label = Label(root, text="Paste Passport Photo")
#Label.place(x=90,y=120)

img = cv2.imread("photo.JPG")
imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgp = Image.fromarray(imgc)
#im=Image.open("photo.JPG")
img = ImageTk.PhotoImage(imgp)
canvas.create_image(30, 30, anchor=NW, image=img)

root.mainloop()

"""******Dialog box simulation (Botton Activation) and return selected file name"""

# Button to open a DialogBox and return file name

from tkinter import * 
from tkinter import filedialog as fd

root = Tk()
root.title('Login')
root.geometry('300x400')

def submitfn():
    filename = fd.askopenfilename()
    print(filename)
    
def closefn():
    root.destroy()

btn1 = Button(root,text = "Browse", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 


btn1.place(x=90, y=280)  
btn2.place(x=170, y=280)

root.mainloop()

# Button to open a DialogBox and return file name
# Click button to select image using PIL

from tkinter import *
from PIL import ImageTk,Image
from tkinter import filedialog as fd
import cv2

root = Tk()
root.title('Login')
root.geometry('300x400')

def submitfn():
    filename = fd.askopenfilename()
    #print(filename)
    
    global img
    im=Image.open(filename)
    img = ImageTk.PhotoImage(im)
    canvas.create_image(30, 30, anchor=NW, image=img)
    
def closefn():
    root.destroy()

canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")
    
btn1 = Button(root,text = "Browse", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

btn1.place(x=80, y=280)  
btn2.place(x=160, y=280)

root.mainloop()

"""******Browse a photo and place on the Canvas using dialog box (but selected pic only )"""

# Button to open a DialogBox and return file name
# Click button to select image using Computer Vision through PIL

from tkinter import *
from PIL import ImageTk,Image
from tkinter import filedialog as fd
import cv2

root = Tk()
root.title('Login')
root.geometry('300x400')

def submitfn():
    filename = fd.askopenfilename()

    global img
    img = cv2.imread(filename)
    imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    im = Image.fromarray(imgc)
    img = ImageTk.PhotoImage(im)
    canvas.create_image(30, 30, anchor=NW, image=img)
    
def closefn():
    root.destroy()

canvas = Canvas(root, width = 300, height = 300)  
canvas.place(x=50,y=50)
canvas.create_rectangle(30, 30, 170, 185,outline="gray")
    
btn1 = Button(root,text = "Browse", command = submitfn,height = 1, width = 7)  
btn2 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

btn1.place(x=80, y=280)  
btn2.place(x=160, y=280)

root.mainloop()

# Create a rectangle of specified size on Canvas Tkinter 
# Insert a Computer Vision image through PIL object (Anothe Approach)
from tkinter import * 
from PIL import ImageTk,Image
import cv2

root = Tk()  
root.geometry('600x800')

#canvas1 = Canvas(root, width = 300, height = 300)  
#canvas2 = Canvas(root, width = 300, height = 300) 
canvas1 = Canvas(root)  
canvas2 = Canvas(root)
canvas1.place(x=50,y=50)
canvas2.place(x=80,y=80)
canvas1.create_rectangle(30, 30, 170, 185,outline="gray")
#canvas2.create_rectangle(70, 70, 170, 185,outline="gray")

#Label = Label(root, text="Paste Passport Photo")
#Label.place(x=90,y=120)

img = cv2.imread("photo.JPG")
imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgp = Image.fromarray(imgc)
#im=Image.open("photo.JPG")
img = ImageTk.PhotoImage(imgp)
canvas2.create_image(30, 30, anchor=NW, image=img)

root.mainloop()

"""******Create two canvas and put two image with resize operation"""

# Simulation of two canvas
# Create a rectangle of specified size on Canvas Tkinter 
# Insert a Computer Vision image through PIL object (Anothe Approach)
# Place both the canvas in appropriate place
# Put rectangle over entire canvas and place image to fit over it through resize
from tkinter import * 
from PIL import ImageTk,Image
import cv2

root = Tk()  
root.geometry('660x500')  # Width x height of GUI

canvas1 = Canvas(root, width = 300, height = 300) # Both canvas widhth and height taken same value 
canvas2 = Canvas(root, width = 300, height = 300) 
#canvas1 = Canvas(root)  
#canvas2 = Canvas(root)
canvas1.place(x=0,y=50)    # Place the canvas
canvas2.place(x=350,y=50)

#canvas1.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)
#canvas2.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)

img = cv2.imread("photo.JPG")
imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgp = Image.fromarray(imgc)
imgp= imgp.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img = ImageTk.PhotoImage(imgp)
canvas1.create_image(5, 5, anchor=NW, image=img)  #(From left, from top)

img1 = cv2.imread("photo.png")
imgc1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
imgp1 = Image.fromarray(imgc1)
#im=Image.open("photo.JPG")
imgp1= imgp1.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img1 = ImageTk.PhotoImage(imgp1)
canvas2.create_image(5, 5, anchor=NW, image=img1)  #(From left, from top)

root.mainloop()

"""******Two canvas with image inside using button control"""

## Simulation of two canvas with button Control

from tkinter import * 
from PIL import ImageTk,Image
import cv2
from tkinter import filedialog as fd

root = Tk()  
root.geometry('660x500')  # Width x height of GUI

def submitfn1():
    filename = fd.askopenfilename()

    global img1
    img1 = cv2.imread(filename)
    imgc1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
    im1 = Image.fromarray(imgc1)
    im1= im1.resize((295,295), Image.ANTIALIAS) # resize(width,height)
    img1 = ImageTk.PhotoImage(im1)
    canvas1.create_image(5, 5, anchor=NW, image=img1)

def submitfn2():
    filename = fd.askopenfilename()

    global img2
    img2 = cv2.imread(filename)
    imgc2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
    im2 = Image.fromarray(imgc2)
    im2= im2.resize((295,295), Image.ANTIALIAS) # resize(width,height)
    img2 = ImageTk.PhotoImage(im2)
    canvas2.create_image(5, 5, anchor=NW, image=img2)
    
def closefn():
    root.destroy()


canvas1 = Canvas(root, width = 300, height = 300) # Both canvas widhth and height taken same value 
canvas2 = Canvas(root, width = 300, height = 300) 
#canvas1 = Canvas(root)  
#canvas2 = Canvas(root)
canvas1.place(x=0,y=50)    # Place the canvas
canvas2.place(x=350,y=50)

canvas1.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)
canvas2.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)

'''
img = cv2.imread("photo.JPG")
imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgp = Image.fromarray(imgc)
imgp= imgp.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img = ImageTk.PhotoImage(imgp)
canvas1.create_image(5, 5, anchor=NW, image=img)  #(From left, from top)

img1 = cv2.imread("photo.png")
imgc1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
imgp1 = Image.fromarray(imgc1)
#im=Image.open("photo.JPG")
imgp1= imgp1.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img1 = ImageTk.PhotoImage(imgp1)
canvas2.create_image(5, 5, anchor=NW, image=img1)  #(From left, from top)

'''
btn1 = Button(root,text = "Image1", command = submitfn1,height = 1, width = 7)
btn2 = Button(root,text = "Image2", command = submitfn2,height = 1, width = 7)  
btn3 = Button(root,text = "Close", command = closefn,height = 1, width = 7) 

btn1.place(x=180, y=370)  
btn2.place(x=280, y=370)
btn3.place(x=380, y=370)

root.mainloop()

## Edge Detection of an Image using Canvas and Button and opencv opearation

from tkinter import * 
from PIL import ImageTk,Image
import cv2
from tkinter import filedialog as fd

root = Tk()  
root.geometry('660x500')  # Width x height of GUI

def submitfn1():
    filename = fd.askopenfilename()

    global img1,orgimg
    orgimg = cv2.imread(filename)
    imgc1 = cv2.cvtColor(orgimg, cv2.COLOR_BGR2RGB)
    im1 = Image.fromarray(imgc1)
    im1= im1.resize((295,295), Image.ANTIALIAS) # resize(width,height)
    img1 = ImageTk.PhotoImage(im1)
    canvas1.create_image(5, 5, anchor=NW, image=img1)
    Label1 = Label(root, text="Original Image")
    Label1.place(x=110,y=30)
    
def submitfn2():
    #filename = fd.askopenfilename()

    global img2, orgimg
    #img2 = cv2.imread(filename)
    imgc2 = cv2.cvtColor(orgimg, cv2.COLOR_BGR2RGB)
    imgr=cv2.cvtColor(imgc2, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(imgr,100,100)

    im2 = Image.fromarray(edges)
    im2= im2.resize((295,295), Image.ANTIALIAS) # resize(width,height)
    img2 = ImageTk.PhotoImage(im2)
    canvas2.create_image(5, 5, anchor=NW, image=img2)
    Label2 = Label(root, text="Edge Detected Image")
    Label2.place(x=450,y=30)
def closefn():
    root.destroy()


canvas1 = Canvas(root, width = 300, height = 300) # Both canvas widhth and height taken same value 
canvas2 = Canvas(root, width = 300, height = 300) 
#canvas1 = Canvas(root)  
#canvas2 = Canvas(root)
canvas1.place(x=0,y=50)    # Place the canvas
canvas2.place(x=350,y=50)

canvas1.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)
canvas2.create_rectangle(5, 5,300, 300,outline="gray")  #(from left, from top, from left, from top)

'''
img = cv2.imread("photo.JPG")
imgc = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
imgp = Image.fromarray(imgc)
imgp= imgp.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img = ImageTk.PhotoImage(imgp)
canvas1.create_image(5, 5, anchor=NW, image=img)  #(From left, from top)

img1 = cv2.imread("photo.png")
imgc1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
imgp1 = Image.fromarray(imgc1)
#im=Image.open("photo.JPG")
imgp1= imgp1.resize((295,295), Image.ANTIALIAS) # resize(width,height)
img1 = ImageTk.PhotoImage(imgp1)
canvas2.create_image(5, 5, anchor=NW, image=img1)  #(From left, from top)

'''
btn1 = Button(root,text = "Browse", command = submitfn1,height = 2, width = 9)
btn2 = Button(root,text = "Edge", command = submitfn2,height = 2, width = 9)  
btn3 = Button(root,text = "Close", command = closefn,height = 2, width = 9) 

btn1.place(x=180, y=370)  
btn2.place(x=280, y=370)
btn3.place(x=380, y=370)

root.mainloop()

import matplotlib.pyplot as plt
import cv2
img = cv2.imread("photo.png")
imgr=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(imgr,100,100)
plt.imshow(edges,cmap='gray')
plt.show()
#imgc2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
    #im2 = Image.fromarray(imgc2)
    #im2= im2.resize((295,295), Image.ANTIALIAS) # resize(width,height)
    #img2 = ImageTk.PhotoImage(im2)
    #canvas2.create_image(5, 5, anchor=NW, image=img2)

# Display an image on GUI using PIL
from tkinter import *  
from PIL import ImageTk,Image  
root = Tk()  
canvas = Canvas(root, width = 300, height = 300)  
canvas.pack()  
img = ImageTk.PhotoImage(Image.open("photo.JPG"))  
canvas.create_image(20, 20, anchor=NW, image=img) 
root.mainloop()

# Plot a figure
import numpy as np
import matplotlib.pyplot as plt

t=np.arange(0,2*np.pi,0.1)
y=np.sin(t)
fig = plt.figure()
plt.plot(t,y)
plt.xlabel("Time")
plt.ylabel("Amplitude")
plt.title("SineWave")
plt.show()
fig.savefig("abc.jpg")

"""******Plot a figure on GUI """

# Plot a figure and save as jpg/png file
# Display thet image on GUI
import numpy as np
import matplotlib.pyplot as plt

t=np.arange(0,2*np.pi,0.1)
y=np.sin(t)
fig = plt.figure()
plt.plot(t,y)
plt.xlabel("Time")
plt.ylabel("Amplitude")
plt.title("SineWave")
#plt.show()
fig.savefig("abc.jpg")
plt.close(fig)

# Display an image on GUI using PIL
from tkinter import *  
from PIL import ImageTk,Image  
root = Tk()  
root.geometry('500x400')
canvas = Canvas(root, width = 300, height = 300)  
canvas.pack()
im=Image.open("abc.jpg")
imgr= im.resize((300,280), Image.ANTIALIAS)
img = ImageTk.PhotoImage(imgr)  
canvas.create_image(10, 10, anchor=NW, image=img) 
root.mainloop()

"""***********Control different plots on GUI"""

# GUI to control different plots

from tkinter import * 
from PIL import ImageTk,Image
import cv2
from tkinter import filedialog as fd
import numpy as np
import matplotlib.pyplot as plt

root = Tk()  
root.geometry('600x400')  # Width x height of GUI

def sinefn():
    global img
    t=np.arange(0,2*np.pi,0.1)
    y=np.sin(t)
    fig = plt.figure()
    plt.plot(t,y)
    plt.xlabel("Time")
    plt.ylabel("Amplitude")
    plt.title("SineWave")
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)

def cosinefn():
    global img
    t=np.arange(0,2*np.pi,0.1)
    y=np.cos(t)
    fig = plt.figure()
    plt.plot(t,y)
    plt.xlabel("Time")
    plt.ylabel("Amplitude")
    plt.title("CosineWave")
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)

    
def imagefn():
    global img
    im=plt.imread('photo.JPG')
    fig = plt.figure()
    plt.imshow(im)
    plt.xticks([])
    plt.yticks([])
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)    
    

def barfn():
    global img
    year=[2015,2016,2017,2018,2019,2020]
    nos=[400,600,700,650,500,680]
    fig = plt.figure()
    plt.bar(year,nos)
    plt.xlabel('Year')
    plt.ylabel('Num of Student')
    plt.title('Admission status over 2015-20')
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)    
    

    
def piefn():
    global img
    fig = plt.figure()
    prog=['C','C++','Python','Java']
    nos=[30,25,45,35]
    plt.pie(nos,labels=prog,autopct='% 1.2f% %',colors=['black','red','green','yellow'],
                                    startangle=0,explode=[0,0,0.1,0]) 
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)     
    
def bubblefn():
    global img
    fig = plt.figure()
    year=[2015,2016,2017,2018,2019,2020]
    nos=[100,600,800,650,500,680]

    plt.scatter(year,nos,s=nos,c=nos) 
    fig.savefig("fig.jpg")
    plt.close(fig)

    im=Image.open("fig.jpg")
    imgr= im.resize((395,295), Image.ANTIALIAS)
    img = ImageTk.PhotoImage(imgr)  
    canvas.create_image(5, 5, anchor=NW, image=img)     


def closefn():
    root.destroy()    
    
canvas = Canvas(root, width = 400, height = 300) # Both canvas widhth and height taken same value 

canvas.place(x=150,y=30)    # Place the canvas


canvas.create_rectangle(5, 5,400, 300,outline="gray")  #(from left, from top, from left, from top)

#im=Image.open("abc.jpg")
#imgr= im.resize((395,295), Image.ANTIALIAS)
#img = ImageTk.PhotoImage(imgr)  
#canvas.create_image(5, 5, anchor=NW, image=img) 

btn1 = Button(root,text = "Sine", command = sinefn,height = 2, width = 9)  
btn2 = Button(root,text = "Cosine", command = cosinefn,height = 2, width = 9)
btn3 = Button(root,text = "Image", command = imagefn,height = 2, width = 9)
btn4 = Button(root,text = "Bar", command = barfn,height = 2, width = 9)
btn5 = Button(root,text = "Pie", command = piefn,height = 2, width = 9)
btn6 = Button(root,text = "Bubble", command = bubblefn,height = 2, width = 9)
btn7 = Button(root,text = "Close", command = closefn,height = 2, width = 9) 

#btn1.place(x=180, y=370)  
btn1.place(x=40, y=10)
btn2.place(x=40, y=60)
btn3.place(x=40, y=110)
btn4.place(x=40, y=160)
btn5.place(x=40, y=210)
btn6.place(x=40, y=260)
btn7.place(x=40, y=310)

root.mainloop()

import matplotlib.pyplot as plt
im=plt.imread('photo.JPG')
fig = plt.figure()
plt.imshow(im)
plt.xticks([])
plt.yticks([])
fig.savefig("fig.jpg")
plt.close(fig)

